name: Update README

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: GitHub-Profile-Summary-Cards
    steps:
      - uses: vn7n24fzkq/github-profile-summary-cards@v0.6.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          
